### ISSUE TITLE
TO-DO

### ISSUE THREAD

**Issue by mawippel** [gustavomerini/escape-filas-backend#2]
- [x] Criar rota de report de fila; (Recebe o nome/id do local)
- [x] Criar rota de localicacao do usuario; (Recebe lat/longitude)
- [x] Converter a lat/longitude no local mais proximo do usuario, registrar a fila nesse local; (https://www.kompulsa.com/node-js-geocoding-example-find-businesses-using-google-places/)
