### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by mawippel** [gustavomerini/escape-filas-backend#3]
- [X] Vincular o User ao report de Location;
- [x] Adicionar campo 'Quantidade' na fila;
- [x] Retornar filas de busca com placeId
- [x] Mudar retorno das filas para: {placeName: String, placeID: String, quantity: Number}

**Comment by wallacetm** [comment]
Feito! Sextou!

**Comment by mawippel** [comment]
Grande dia!
